//GET https://www.googleapis.com/youtube/v3/channels

GET https://localhost:3001/token?code=4/0AY0e-g46TUjtgpS1TWWQEQJigvhy-6R0mSgZvZ_E5V2mLEI2ijWg7sEq4PRReLsWlmQSsw

GET http://admin:admin@192.168.1.76:5984/_up

###
# CREATE A DB

PUT http://admin:admin@127.0.0.1:5984/users

###
# CHECK DB

GET http://admin:admin@127.0.0.1:5984/_all_dbs

###
# DELETE A DB

DELETE http://admin:admin@127.0.0.1:5984/yt_test_db

###
# CREATE a DOC

PUT http://admin:admin@192.168.1.76:5984/my_database_2/5
content-type: application/json

{
    "name": "andrea",
    "surname": "vitaletti"
}

###
#list all docs in the DB
GET http://admin:admin@127.0.0.1:5984/users/_all_docs

###
# GET CONTENT OF A DOC
GET http://admin:admin@127.0.0.1:5984/users/4268688203170663

### NON-EXISTENT GET
GET http://admin:admin@127.0.0.1:5984/yt_test_db_user/s

###
# UPDATE A DOC
PUT http://admin:admin@127.0.0.1:5984/users/4268688203170663

{
    "_rev": "6-4f09e8a605761323a1336ca205ca3a2a",
    "nome": "Laaners"
}

###
# DELETE a DOC

DELETE http://admin:admin@127.0.0.1:5984/my_database/1?rev=2-c8d48abcb0f00e5976dd3f6cd91be3ab

###
GET http://api.coronatracker.com/v5/analytics/newcases/country?countryCode=AU&startDate=2020-04-01&endDate=2020-05-01

###
GET https://www.google.com/search?q=kirby&tbm=isch&ie=utf-8&oe=utf-8&sclient=gws-wiz

###
GET http://admin:admin@127.0.0.1:5984/users/_all_docs?include_docs=true

###
GET http://admin:admin@127.0.0.1:5984/users/_all_docs

###
GET http://admin:admin@127.0.0.1:5984/users/4268688203170663

###
GET http://admin:admin@127.0.0.1:5984/itineraries/BKK_AAR_2021-08-01_1019.80_EUR_PT18H45M_2021-06-28

###
GET http://api.coronatracker.com/v3/stats/worldometer/country?countryName=Jersey

###
GET http://api.coronatracker.com/v1/travel-alert?countryCode=FR

###
GET https://127.0.0.1:3000/api/tuttiItinerari?destination=aar&origin=bkk

###
GET https://127.0.0.1:3000/api/itinerariDatiCovid

###
GET https://127.0.0.1:3000/api/datiCovidPaesi

###
GET https://127.0.0.1:3000/api/datiCovidPaesi?countries=New%20Caledonia

###
GET https://127.0.0.1:3000/api/datiCovidPaesi?countries[0]=THAILAND&countries[1]=New%20Caledonia

###
GET https://127.0.0.1:3000/api/datiCovidPaesi?countries[0]=THAILAND&countries[1]=UNITED%20ARAB%20EMIRATES

###
GET https://graph.facebook.com/v11.0/335247768157626/picture?redirect=false

###
GET https://localhost:3000/airline_data?code=QR